name: security-agent-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytest
  - pip:
    - black
    - flake8
    - pre-commit
    - python-dotenv
    - fastapi
    - uvicorn
    - langchain
    - langchain-community
    - langchain-core
    - langchain-huggingface
    - langchain-postgres
    - langchain-text-splitters
    - langchain-ollama
    - pypdf
    - pgvector
    - psycopg-binary
    - sentence-transformers